services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      PORT: ${BACKEND_PORT:-3000}
      MONGODB_URI: mongodb://mongodb:27017/antifa-bookclub
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${BACKEND_PORT_HOST:-4100}:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4100/api}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
