name: Validate main branch

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality-gate:
    name: Lint, test, typecheck, build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine base ref
        id: base
        env:
          BEFORE: ${{ github.event.before }}
        run: |
          if git rev-parse "$BEFORE^{commit}" >/dev/null 2>&1; then
            echo "mode=affected" >> "$GITHUB_OUTPUT"
            echo "base=$BEFORE" >> "$GITHUB_OUTPUT"
          elif git rev-parse HEAD^ >/dev/null 2>&1; then
            echo "mode=affected" >> "$GITHUB_OUTPUT"
            echo "base=$(git rev-parse HEAD^)" >> "$GITHUB_OUTPUT"
          else
            echo "mode=all" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Nx affected targets
        if: steps.base.outputs.mode == 'affected'
        env:
          NX_DAEMON: 'false'
        run: >
          pnpm exec nx affected -t lint,test,typecheck,build
          --base=${{ steps.base.outputs.base }}
          --head=${{ github.sha }}

      - name: Run Nx targets for entire workspace
        if: steps.base.outputs.mode == 'all'
        env:
          NX_DAEMON: 'false'
        run: >
          pnpm exec nx affected -t lint,test,typecheck,build --all
